#!/bin/bash

# remove bloat
apt remove --purge -y firefox
apt remove --purge -y transmission-common
apt remove --purge -y pidgin
apt remove --purge -y parole
apt remove --purge -y xfburn
apt remove --purge -y evince

# update, upgrade
apt update;
apt upgrade -y;
# apt full-upgrade # for drivers?
apt autoremove -y

## INSTALL LIBRARIES ##
# Dev
apt install -y curl
apt install -y apt-transport-https
apt install -y cmake
apt install -y make
apt install -y git-core
apt install -y autoconf
apt install -y automake
apt install -y build-essential
apt install -y libssl-dev
apt install -y zlib1g-dev
apt install -y libbz2-dev
apt install -y libreadline-dev
apt install -y libsqlite3-dev
apt install -y wget
apt install -y curl
apt install -y llvm
apt install -y libncurses5-dev
apt install -y xz-utils
apt install -y tk-dev

# Media
apt install -y exfat-*
apt install -y flac
apt install -y lame
apt install -y x264
apt install -y unrar

# Misc

apt update
apt upgrade -y
apt autoremove -y

## INSTALL APPS ##

# Dev/Utils
apt install -y htop
apt install -y guake
apt install -y vim
apt install -y zsh
apt install -y tmux
apt install -y tree

# Essential
apt install -y chromium-browser
apt install -y psensor
apt install -y vlc
apt install -y okular
apt install -y nomacs
apt install -y gparted
apt install -y tlp
apt install -y deluge

# Dictionary
apt install -y dict
apt install -y dictd
apt install -y dict-gcide
apt install -y dict-wn

## Make directories ##
# Make home dirs
cd
mkdir Soft Media Projects Work Data

# Media
cd ~/Media && mkdir Images Music Videos
cd Images && mkdir Aes MiscImg Pictures && cd

# Documents
cd ~/Documents
mkdir Books Correspondence Course MiscDocs Official Reading Receipts Writing
cd Books && mkdir Textbooks eBooks && cd ..
cd Official && mkdir Health Immigration Records && cd ..
cd Reading && mkdir Papers PaperNotes && cd

# Projects
cd ~/Projects
mkdir Archived Inactive Interview MiscProj
cd Interview && mkdir Companies Prep && cd

# Soft
cd ~/Soft && mkdir Installed DevStuff
cd DevStuff && mkdir Misc Py Tools && cd ..
cd Installed && mkdir Apps MiddleWare Themes Utils && cd



## Add repo/sources apps ##

# oh my zsh
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)";
cp ~/.zshrc ~/.zshrc.bkp

## sublime stuff
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -;
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list;
apt update;
apt install -y sublime-text;

# Ghostwriter
add-apt-repository ppa:wereturtle/ppa
apt update
apt install ghostwriter

# Pyenv
curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash;
echo '# Pyenv stuff' >~/.zshrc
echo 'export PATH="/home/evan/.pyenv/bin:$PATH"' >~/.zshrc
echo 'eval "$(pyenv init -)"' >~/.zshrc
echo 'eval "$(pyenv virtualenv-init -)"' >~/.zshrc
source ~/.zshrc

## pyenv stuff
pyenv update
pyenv install 3.6.6
pyenv install miniconda-latest
pyenv virtualenv 3.6.6 ^
pyenv local ^
pip install -U pip setuptools
pip install numpy
pip install scipy
pip install sklearn
pip install matplotlib
pip install ipython
pip install jupyter
pip install jupyterthemes
pip install chainer
#pip install tangent # installs tf-nightly, so do TF first

# Z jump around
cd && cd ~/Soft/Installed/Utils/
git clone https://github.com/rupa/z.git z_jump
echo '# z jump around' >~/.zshrc
echo '. /home/evan/Soft/Installed/Utils/z_jump/z.sh' >~/.zshrc
cd

# Themes
# Arc-grey
cd ~/Soft/Installed/Themes/
git clone https://github.com/eti0/arc-grey-theme --depth 1 && cd arc-grey-theme
./autogen.sh --prefix=/usr
make install
cd

# paper icons
add-apt-repository -u ppa:snwh/ppa
apt update
apt install paper-icon-theme


#sudo add-apt-repository ppa:xubuntu-dev/extras; # kind of clunky
#sudo apt update;
#sudo apt install -y xfdashboard;


# FINISHING
update-ca-certificates -f
apt update
apt upgrade -y
apt autoremove -y

echo "FINISHED"


# GET TF WHEEL FROM https://github.com/mind/wheels
#pip install --no-cache-dir <*.whl link>
#jt -t onedork -fs 12 -f ubuntu -altp -tfs 11 -nfs 115 -cellw 90% -T -N


# Keyboard shortcuts:
# amixer set Master 5%+ # Alt + =
# amixer set Master 5%- # Alt + -
# subl # super+E
# xfce4-screenshooter # print
# xfce4-popup-whiskermenu # super+R

# sshfs name@server:/path/to/folder /path/to/mount/point



# mozc
#If you have Xubuntu 16.04 installed and want to be able to type Japanese, try the following steps:
#1. Go to "Settings" and then "Language Support": click the button "install/remove languages" and choose Japanese.
#2. Change the "Keyboard input method system" (same menu) to "fcitx". "Close" window.
#3. Go to "Keyboard", choose the "Layout" tab, and "Add" Japanese. Make sure "use system default" is untoggled. "Close" window (I'm not sure this step is necessary, but I did it anyway)
#4. Go to "Settings" and then "Fcitx Configuration", under the tab "Input method" click "+". Untoggle "only show current language" and choose "Mozc Japanese" from the list. (I had to scroll throught the entire list to find this. It doesn't start with "Keyboard - " like the other options.)
#5. Go to the tab "Global config" in the same window and look which keys trigger the Japanese input method. The default on my computer is CTRL+Space. Alternatively, a keyboard icon should be visible in the panel where you can select "Input method" - "Mozc"
#I admit to restarting my computer a few times inbetween some of the steps. I'm not sure if it is necessary.
#I don't remember ever installing "Mozc" and "Fcitx", I think they came with the system/Japanese language support.

# in Language Support > regional formats > display numbers usual format for japanese
# orage clock format: %x %R
# https://www.linuxquestions.org/questions/slackware-14/xfce-clock-custom-formatting-codes-753433/
# previous: %d %b, %H:%M
