

Bloat:
- "*mate-desktop*"
- mugshot
- cheese-common
- libgnome-games-support-common
- "*firefox*"
- "transmission-*"
- "*pidgin*"
- "*parole*"
- "*xfburn*"
- "*libreoffice*"
- "*hplip*"
- "snapd*"
- "*thunderbird*"
- "*yelp*"
- printer-driver-splix
- printer-driver-sag-gdi
- printer-driver-pxljr
- printer-driver-ptouch
- printer-driver-pnm2ppa
- printer-driver-min12xxw
- printer-driver-m2300w
- printer-driver-foo2zjs-common
- printer-driver-foo2zjs
- printer-driver-c2esp

