
essentials:
- numpy
- scipy
- sklearn
- matplotlib
- chainer
- ipython
- jupyter
- notebook
- gitup


science-math:
- autograd  # easier to use than sympy; less powerful though
- sympy  # learning curve, but amazingly powerful and featured
- scikit-video
- pydataset  # access to many datasets, in dataframe format
- pandas
#- primesieve # always freezes install


GPU:
- pycuda  # unofficial cython-like embedded cuda code
- cupy


AI-frameworks:
- gym
- chainerrl
- neupy  # ANN library, TF backend, lib has some cool stuff


TF-dependencies:  # don't actually use any of it, just to build TF
- keras
- keras-applications
- keras-preprocessing
- protobuf

NLP-stuff:
- nltk  # de-jure natural language library
- spacy # NLP library
- snowballstemmer # library of stemming algs

starcraft-games:
- s2clientprotocol  # linux sc2 client (headless)
- pysc2   # "official" deepmind sc2 api, fairly verbose and buggy, no documentation
- sc2     # user-made sc2 api, (python-sc2), popular, also no documentation
- scbw    # bw on linux (in docker container)
- pygame  # dependency for every game-related thign

visualization:
- ipyvolume    # <-------<< WOW! looks comparable to mayavi ###########################
- bokeh

notebook:
- ipython
- jupyter
- notebook
- jupyterthemes
- jupyter-contrib-nbextensions  # HUGE enhancements to notebook capabilities
- jupyter_nbextensions_configurator
# Then activate:
# $ jupyter contrib nbextension install --user
# $ jupyter nbextensions_configurator enable --user


apps:
- retext  # RST and MD editor, best desktop editor for RST, still kinda bad
- buku  # CLI bookmark manager, havent used
- jrnl  # *** CLI journaling/notes app, supports encryption,
- termdown  # simple countdown/timer terminal, ncurses
- apt-select  # pings apt mirrors, gives list fastest


lib-enhancements:
- attrs       # manages a few dunders (mostly init), not that big of a deal
- bidict      # exactly what it sounds like
- python-box  # has surprising amount of different "boxes" or dict-classes


dev:
- cookiecutter  #*** project boilerplate
- nose     # tests
- flake8   # linting/static code, better than pylint
- radon    # linting/code metrics, better than flake8
- coverage # code-coverage
- black    # auto-format code to style, ONLY used on othre people's gross code
- luigi    # manages task pipeline


net:
- html5lib  # dep
- bs4       # scrape
- you-get   # scrape for dummies


deps-utils:
- binarytree  # make arbitrary binary trees to work/study/play with
- h5py    # h5 serialization
- hickle  # ..another serialization, no noticed benefits over pickle yet
- pyqt5
- pillow
- pycurl
- pygments
- vermin      # AWESOME, automatically test python version support in project
- pipdeptree  # shows deps like tree cmd
- johnnydep   # awesome, lists dependencies of a package


pypi-python:
- pypi-cli  # decent utils in `pypi info <pkg>` and `pypi search`
- pip-autoremove  #*** remove a package and the packages it installed as deps


docs-text:
- docutils
- doc2dash # making zeal datasets
- pypandoc # pandoc wrapper
- textdistance[extras]  # bunch of different text diff algos
- rstwatch  # automatically makes html conversions when change detected
- rstdiary  # duno?

parsers:
- feedparser      #$ universal feed parser
- jupyter-parser  # CLI tool for parsing jupyter notebooks
- mistune         # markdown

media:
- scdl  # soundcloud downloader

sphinx:
- sphinx
- sphinx-rtd-theme
- sphinxcontrib-jupyter
- sphinxcontrib-websupport
- sphinxcontrib-bibtex # allows bibtex to be inserted into sphinx doc
- numpydoc  # sphinx extension to support docstrings in numpy format
- pelican   # static site generator for blog; py api, rst, django


reading:
    bibtex:
        - pybtex
        - bibtexparser
        - bibcure
        - doi2bib    # exactly what it sounds like
        - betterbib  # fetches info to try and correct/format your bib
        - pybtex-docutils
    arxiv:
        - scihub2pdf
        - arxivcheck
        - arxivscraper
        - arxiv # main python source for arxiv.py API
        - arxiv_download
        - arxiv2txt  # SCRIPT not pypi?

arg-parsers: # I prefer argparse/argv in general, to keep dependencies down
- fire   # IF I opt for diff argparser, fire is the shit (args req'd tho)
- docopt # more work than you think
- click  # fuck that stack of decorators, why peep like???


CLI-shell:
- thefuck     # AWESOME, correct previous command
- cheat       # decent man examples for queried cmd
- maybe       # hit-or-miss, test out what command will do
- glances     # better top/htop
- archivenow  # archives urls (WARC, all the archiving sites)
- halo        # spinners for terminal, ipython, notebook


git-github:
- GitPython           # python git library
- pygithub            # github API v3, unofficial
#- github3.py         # github API, official (i think)
- starred             # dope (make your own awesome list from your stars)
- oh-my-stars         # cli tool to search your stars
- gitsuggest          # suggest repos of interest based on your stars
- grip                # preview md rendering on github before publishing
- gitstars            # django app to manage your stars
- github-backup       # backup repos from user or organization
- github-sync         # download /pull from all your git repos
- github-trending     # trending repos and users on github
- clone-github        # clone github repos in bulk
- replicate-github    # tool for maintaining mirrors of github repos
- github-trending-cli # View Github Trending and README from the command line


ascii-art:
- pyfiglet  # same as figlet, just implemented in python
- art       # decent 1-liner and text art ascii (text is figlet)


misc-untested:
- birdseye    # graphical debugger, easily evaluat values
- SetSimilaritySearch # python, similarity score between sets
- rebound-cli  # hasn't ever worked, always f'n broken
- pyviz        # visualization lib i think
- astrodash    # spectral convolutions deep learning supernovae
- pipsalabim   # guesses your dependencies, no need for req file
- dbcollection # collection of popular ML datasets
- smmap2       # pure python sliding window
- title2bib    # generate bibtex given title

