---

ORDER_OF_OPS:
    - Bloat
    - apt:
        - setup
        - deps:
            - GCC
            - utils
        - Apps
        - PPA
    - pyenv
    - NPM
    - Nativefier

Bloat:
- "*mate-*"
- mugshot
- cheese-common
- libgnome-games-support-common
- "*firefox*"
- "transmission-*"
- "*pidgin*"
- "*parole*"
- "*xfburn*"
- "*libreoffice*"
- "*hplip*"
- "snapd*"
- "*thunderbird*"
- "*yelp*"
- printer-driver-splix
- printer-driver-sag-gdi
- printer-driver-pxljr
- printer-driver-ptouch
- printer-driver-pnm2ppa
- printer-driver-min12xxw
- printer-driver-m2300w
- printer-driver-foo2zjs-common
- printer-driver-foo2zjs
- printer-driver-c2esp
- fonts-tlwg*
- fonts-thai*
- fonts-liberation*
- fonts-smc*
- fonts-liberation2*
- fonts-kacst*
- fonts-samyak*
- fonts-lao*
- fonts-deva*
- fonts-gujr*
- fonts-knda*
- fonts-guru*
- fonts-navilu*
- fonts-orya*
- fonts-beng*
- fonts-khmeros*
- fonts-mlym*
- fonts-lklug*
- fonts-sil*
- fonts-taml*
- fonts-sahadeva*
- fonts-sarai*
- fonts-lohit*
- fonts-gubbi*
- fonts-nakula*
- fonts-telu*
- fonts-kalapi*
- fonts-indic*
- fonts-gargi*
- fonts-pagul*
- fonts-noto*

apt:
    setup:
        - apt-fast
        - zsh
    deps:
        GCC:
            - gcc-7 # GCC should trigger
            - g++-7
            - gcc-8
            - g++-8
        utils:
            - wget
            - curl
            - git-core
            - apt-transport-https
            - autoconf
            - automake
            - build-essential
            - cmake
            - docbook2x
            - dvipng
            - extra-cmake-modules
            - gfortran
            - graphviz
            - imagemagick
            - libarchive-dev
            - libatomic1
            - libbz2-dev
            - libcurl4-openssl-dev
            - libncurses5-dev
            - libreadline-dev
            - librsvg2-bin
            - libre2-dev
            - libsqlite3-dev
            - libssl-dev
            - libxcb-keysyms1-dev
            - llvm
            - m4
            - make
            - p7zip-full
            - p7zip-rar
            - perl
            - pkg-config
            - python-sphinx
            - qt5-default
            - qt5-qmake
            - redis-server
            - redis-tools
            - texlive-xetex
            - tk-dev
            - xclip
            - xz-utils
            - zlib1g-dev

    Apps:
        - vim
        - anki
        - chromium-browser
        - flameshot
        - inkscape
        - git-extras
        #- pdfsam  # install from deb; apt outdated
        - vlc
        - mpv
        - gparted
        - deborphan
        - aria2
        - deluge
        - git-crypt
        - img2pdf
        - wkhtmltopdf
        - xsensors
        - xfce4-timer-plugin
        - xfce4-sensors-plugin
        - xdotool
        - redshift
        - zstd
        - htop
        - tree
        - nomacs
        - tlp
        - printer-driver-brlaser
        - exfat-utils
        - flac
        - lame
        - x264
        - sshfs
        - openssh-client
        - autossh
        - unar
        - unrar
        - dictd
        - dict-gcide
        - dict-wn
        - fonts-hack
        - fonts-opensymbol
        - fonts-symbola
        - fonts-sil-gentiumplus
        - fonts-freefont-ttf
        - fonts-stix # math symbols
        - texlive-latex-recommended
        - fonts-umeplus
        - fonts-hanazono
        - fonts-mplus
        - fonts-mikachan

    PPA:
        - git-core/ppa
        - wereturtle/ppa

Env:
    commands:
        - sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"  # OH-MY-ZSH
        - mkdir -p ~/.Dots/Keys ~/.Apps ~/Projects



pyenv:
    setup:
        commands:
            - "curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash;"
            - echo 'export PATH="$USER/.pyenv/bin:$PATH"' >> ~/.zshrc
            - echo 'eval "$(pyenv init -)"' >> ~/.zshrc
            - echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.zshrc
            - source ~./zshrc
            - pyenv install 3.7.1
            - cd ~
            - pyenv virtualenv 3.7.1 ^
            - pyenv local ^


NPM:
    - setup:
        commands:
            - "curl -L https://git.io/n-install | N_PREFIX=~/.n bash -s -- -y"
            - "n lts"
    - next:
        - nativefier
        - tldr


Nativefier:
    Gmail: https://mail.google.com
    Google-Drive: https://drive.google.com
    Google-Keep: https://keep.google.com
    Google-Calendar: https://calendar.google.com
    Deepmind: https://deepmind.com/blog/
    OpenAI: https://blog.openai.com/
    Google-AI: https://ai.google/research/pubs/
    Simply-Hired: https://www.simplyhired.com/
    LinkedIn: https://www.linkedin.com/uas/login
    Airtable: https://airtable.com/
    Hacker-Rank: https://www.hackerrank.com/dashboard

# Self-install
# ============
# All software that either requires more steps to be installed through
#  pkg manager, or is not installed via a package manager
# NB: *always* get the AppImage over deb, and deb over anything else
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -;
echo "deb https://download.sublimetext.com/ apt/stable/" | tee /etc/apt/sources.list.d/sublime-text.list;

self-install: # software not installed via a package manager
    - sublime:
        commands:
            - wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -;
            - echo "deb https://download.sublimetext.com/ apt/stable/" | tee /etc/apt/sources.list.d/sublime-text.list;
            - apt update && apt install sublime-text

    - z:
        commands:
            - mkdir -p ~/.Apps/Z_jump
            - wget -O ~/.Apps/Z_jump/z.sh https://raw.githubusercontent.com/rupa/z/master/z.sh
            - echo ". $HOME/.Apps/Z_jump/z.sh" >> ~/.zshrc

    - fzf:
        commands:
            - git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
            - ~/.fzf/install

    - croc:
        commands:
            - curl https://getcroc.schollz.com | bash

    - superproductivity:
        commands:
            - cd ~/.Apps
            -  curl --silent "https://api.github.com/repos/johannesjo/super-productivity/releases/latest" |
               grep '"tag_name":' |
               sed -E 's/.*"([^"]+)".*/\1/' |
               xargs -I {} curl -sOL "https://github.com/johannesjo/super-productivity/archive/"{}'.AppImage'

    - joplin:
        # joplin installs itself in HOME root anyway
        commands:
            - cd ~/.Apps
            - wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash
