"""
Preservation of one-off scripts used for some purpose, that
might be useful again some time.

"""

#██████████████████████████████████████████████████████████████████████████████
#-----------------------------------------------------------------------------#
#                                  pylibgen                                   #
#-----------------------------------------------------------------------------#
import subprocess
from slugify import slugify
from pylibgen import Library

def fname_book(book):
    title = slugify(book.title)
    fname = title + '.pdf'
    return fname

def get_book(book):
    fname = fname_book(book)
    subprocess.run(f'wget -O {fname} {book.get_url()}', shell=True)

l = Library()

def search(isbn):
    ids = l.search(isbn)
    if len(ids) == 0:
        print('No results!')
        return
    books = list(l.lookup(ids))
    for i, b in enumerate(books):
        if b.extension != 'pdf':
            continue
        print(f'BOOK {i}')
        pprint(vars(b))
        print('\n')
    bidx = input('Download book: ')
    if bidx:
        #assert bidx.isdigit() # its just u
        book = books[int(bidx)]
        get_book(book)
    return




#██████████████████████████████████████████████████████████████████████████████
#-----------------------------------------------------------------------------#
#                             Combining src files                             #
#-----------------------------------------------------------------------------#

from glob import glob

task_dirs  = {d.split('/')[-1]: [] for d in glob('common-tasks/*')}
task_fpaths = glob('common-tasks/*/*')

for fp in task_fpaths:
    key = fp.split('/')[1]
    task_dirs[key].append(fp)

concatted_fname = 'common_tasks.cpp'


line = '//' + '='*76 + '//'

soft_line = "\n// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n\n"

def get_header_line(topic):
    header = f"\n\n{line}\n// {topic:^74} //\n{line}\n\n"
    return header


def write_file():
    with open(concatted_fname, 'w') as wfile:
        for k, v in task_dirs.items():
            cur_header = get_header_line(k)
            wfile.write(cur_header)
            for fpath in v:
                with open(fpath) as cpp_file:
                    for line in cpp_file.read():
                        wfile.write(line)
                wfile.write(soft_line)

#██████████████████████████████████████████████████████████████████████████████
#-----------------------------------------------------------------------------#
#                Extracting all pdf copies attached in Zotero                 #
#-----------------------------------------------------------------------------#

import os
import glob
import shutil

# paths
dst  = os.environ['HOME'] + '/LITERATURE'
srcs = [os.path.abspath(g) for g in glob.glob('./**/*.pdf', recursive=True)]

# copy
def srcs2dst(srcs, dst):
    if not os.path.exists(dst):
        os.makedirs(dst)
    for s in srcs:
        sname = s.split('/')[-1]
        shutil.copy(s, dst)
        print(f'Moved {sname}')

#srcs2dst(srcs, dst)


#██████████████████████████████████████████████████████████████████████████████
#=============================================================================#
#                             Make *.desktop file                             #
#=============================================================================#

from datetime import datetime
import fire
import pyperclip
import utils


cli = argparse.ArgumentParser()
cli.add_argument('-b', '--bin_path', )

'''
[Desktop Entry]
Name=Stencila
Comment=Stencila for the desktop
Exec="/home/evan/.Apps/appimgs/stencila-desktop-0.28.2-x86_64.AppImage" %U
Terminal=false
Type=Application
Icon=appimagekit-stencila-desktop
X-AppImage-Version=0.28.2
X-AppImage-BuildId=43f61110-6532-11a8-199d-759e9fc91f92
Categories=Utility;
X-Desktop-File-Install-Version=0.23
X-AppImage-Comment=Generated by /tmp/.mount_stenciWSJhjh/AppRun
TryExec=/home/evan/.Apps/appimgs/stencila-desktop-0.28.2-x86_64.AppImage
'''

# Desktop file
DESKTOP_ENTRY = """\
[Desktop Entry]
Name={name}
Comment={comment}
Exec={exe}
Terminal=false
Type=Application
Icon={icon}
Categories={categories};
"""

def get_field(field, default=''):
    field = field.title() + '='
    value = input(field)
    if value == '' and default:
        value = default
    entry = field + value
    return entry

def get_exe():
    pass

def get_entry():
    print('[Desktop Entry]')
    name    = get_field('name')
    comment = get_field('comment')
    exe     = get_field('Exec')

    name = 'Name=' + input('Name=')
    comment = 'Comment'

categories = ['Development',
              'Education',
              'Graphics',
              'Internet',
              'Multimedia',
              'Office',
              'System'
              ]

def get_categories():
    prompt  = "\nPlease select any applicable categories:\n"
    cat_sel = '  \n'.join([f"{i}: {c}" for i,c in enumerate(categories)])
    prompt += cat_sel + '\n > '
    sel = input(prompt)
    if sel == '':
        cats = 'Other;'
    else:
        cats = ';'.join([categories[i] for i in map(int, list(sel))])
    return cats




bidx = input('Download book (i/N): ')

def write_desktop_file(name):
    title = name.title()
    desktop_entry = DESKTOP_ENTRY.format(title=title, name=name)
    with open(desktop_path + f'/{name}.desktop', 'w') as dfile:
        dfile.write(desktop_entry)
    print(f"Wrote desktop entry:\n{desktop_entry}")





#██████████████████████████████████████████████████████████████████████████████
#-----------------------------------------------------------------------------#
#                               PyPi API stuff                                #
#-----------------------------------------------------------------------------#
"""
NOTE: the PyPi API no longer provides download numbers
"""

import requests

api_res = requests.get('https://pypi.org/pypi/numpy/json')
res_json = api_res.json()
res_json.keys() # dict_keys(['info', 'last_serial', 'releases', 'urls'])

print(res_json['info'])
{'author': 'Travis E. Oliphant et al.',
 'author_email': '',
 'bugtrack_url': None,
 'classifiers': ['Development Status :: 5 - Production/Stable',
                 'Intended Audience :: Developers',
                 'Intended Audience :: Science/Research',
                 'License :: OSI Approved',
                 'Operating System :: MacOS',
                 'Operating System :: Microsoft :: Windows',
                 'Operating System :: POSIX',
                 'Operating System :: Unix',
                 'Programming Language :: C',
                 'Programming Language :: Python',
                 'Programming Language :: Python :: 2',
                 'Programming Language :: Python :: 2.7',
                 'Programming Language :: Python :: 3',
                 'Programming Language :: Python :: 3.4',
                 'Programming Language :: Python :: 3.5',
                 'Programming Language :: Python :: 3.6',
                 'Programming Language :: Python :: 3.7',
                 'Programming Language :: Python :: Implementation :: CPython',
                 'Topic :: Scientific/Engineering',
                 'Topic :: Software Development'],
 'description': 'It provides:\n'
                '\n'
                '- a powerful N-dimensional array object\n'
                '- sophisticated (broadcasting) functions\n'
                '- tools for integrating C/C++ and Fortran code\n'
                '- useful linear algebra, Fourier transform, and random number '
                'capabilities\n'
                '- and much more\n'
                '\n'
                'Besides its obvious scientific uses, NumPy can also be used '
                'as an efficient\n'
                'multi-dimensional container of generic data. Arbitrary '
                'data-types can be\n'
                'defined. This allows NumPy to seamlessly and speedily '
                'integrate with a wide\n'
                'variety of databases.\n'
                '\n'
                'All NumPy wheels distributed on PyPI are BSD licensed.\n'
                '\n'
                '\n'
                '\n',
 'description_content_type': '',
 'docs_url': None,
 'download_url': 'https://pypi.python.org/pypi/numpy',
 'downloads': {'last_day': -1, 'last_month': -1, 'last_week': -1},
 'home_page': 'https://www.numpy.org',
 'keywords': '',
 'license': 'BSD',
 'maintainer': 'NumPy Developers',
 'maintainer_email': 'numpy-discussion@python.org',
 'name': 'numpy',
 'package_url': 'https://pypi.org/project/numpy/',
 'platform': 'Windows',
 'project_url': 'https://pypi.org/project/numpy/',
 'project_urls': {'Download': 'https://pypi.python.org/pypi/numpy',
                  'Homepage': 'https://www.numpy.org'},
 'release_url': 'https://pypi.org/project/numpy/1.16.2/',
 'requires_dist': None,
 'requires_python': '>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*',
 'summary': 'NumPy is the fundamental package for array computing with Python.',
 'version': '1.16.2'}
