# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Chest
author: evdcush
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: chest.tex

# Add a bibtex file so that we can create citations
# DISABLED DUE TO UNFIXED BUG RELATED TO DOCUTILS.
#   If you enable, the layout gets broken
#bibtex_bibfiles:
#  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/evdcush/Chest  # Online location of your book
  path_to_book: Docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true
  #favicon: favicon.ico

# ------

# Custom config
# =============

# Sphinx
# sphinx:
#   config:
#     html_theme_options:
#       # Configure logos based on color theme.
#       logo:
#         image_light: logo_for_light_theme.svg
#         image_dark: logo_for_dark_theme.svg
